### ISSUE TITLE
Configure pool neofs-nodes

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/restic#12]
Consider support configuration more than one neofs-node in repository string 
```
neofs:grpc://s01.neofs.devenv:8080/BQuLfh5yPSWLRsoRGtvqg8itXRREN17dgmHDsw1yLJgb
```

For example we can use previous one with the `1` priority. And add other endpoint in options with the `2` priority (but in this case we should be sure `restic` tries make another requests when fails the first one (otherwise pool will never use the endpoints with `2` priority))

**Comment by alexvanin** [comment]
Add example of different configurations in this issue.

**Comment by KirillovDenis** [comment]
I think we can use the following configuration:
```
neofs:BQuLfh5yPSWLRsoRGtvqg8itXRREN17dgmHDsw1yLJgb \
 -o neofs.endpoint=grpc://s01.neofs.devenv:8080,1,1 \
 -o neofs.endpoint=grpc://s02.neofs.devenv:8080,2,1 \
 -o neofs.endpoint=grpc://s03.neofs.devenv:8080,3,9 
```
The `neofs.endpoint` will have the format `<endpoint>,<priority>,<weight>`  and be required (or we can have some default endpoint to testnet/mainnet for example).

**Comment by KirillovDenis** [comment]
Actually we cannot use the same option more than once. So we should use:
```
neofs:BQuLfh5yPSWLRsoRGtvqg8itXRREN17dgmHDsw1yLJgb \
 -o neofs.endpoints="grpc://s01.neofs.devenv:8080 1 1; grpc://s02.neofs.devenv:8080 2 1; grpc://s03.neofs.devenv:8080 3 9"
```

Similar to the same parameters in [rclone](https://github.com/nspcc-dev/rclone/issues/9)

@alexvanin

**Comment by alexvanin** [comment]
Are these going to be correct configurations?

```
1. neofs:[cid] -o neofs.endpoints="grpc://s01.neofs.devenv:8080"
2. neofs:[cid] -o neofs.endpoints="grpc://s01.neofs.devenv:8080 1; grpc://s02.neofs.devenv:8080 2"
3. neofs:[cid] -o neofs.endpoints="grpc://s01.neofs.devenv:8080 1 1; grpc://s02.neofs.devenv:8080 2 1; grpc://s02.neofs.devenv:8080 2 9"
```

**Comment by KirillovDenis** [comment]
> Are these going to be correct configurations?

I suppose the third configuration has typo (the third endpoint should be `s03`). If so then such configurations are going to be correct.

**Comment by alexvanin** [comment]
Done in #15
