### ISSUE TITLE
Support native compression

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/restic#9]
The latest restic release has native compression https://restic.net/blog/2022-08-25/restic-0.14.0-released/

At the first glance, this is done on the client side and it would be nice to support it here:
1. Put object in NeoFS with `application/zstd` xheader if native compression is used.
2. Mention `compression_exclude_content_types` setting for neofs-node in the README.

**Comment by alexvanin** [comment]
Interesting scheme for compression:
- try to compress first 15-20 KiB
- if compression rate is sufficient, then compress the object, else ignore.

**Comment by alexvanin** [comment]
Closed in #11
